//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SysAngular.Models
{
   
    
    public partial class categoria_chamado
    {
        public int cat_cod { get; set; }
        public string cat_nome { get; set; }
    }
}
