//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SysAngular.Models
{
    
    
    public partial class cliente
    {
        public int cli_cod { get; set; }
        public string cli_nome { get; set; }
        public string cli_cpfcnpj { get; set; }
        public string cli_rgie { get; set; }
        public string cli_rsocial { get; set; }
        public Nullable<int> cli_tipo { get; set; }
        public string cli_cep { get; set; }
        public string cli_endereco { get; set; }
        public string cli_bairro { get; set; }
        public string cli_fone { get; set; }
        public string cli_cel { get; set; }
        public string cli_email { get; set; }
        public string cli_endnumero { get; set; }
        public string cli_cidade { get; set; }
        public string cli_estado { get; set; }
    }
}
