//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SysAngular.Models
{
    
    
    public partial class erp_lcEntities : DbContext
    {
        public erp_lcEntities()
            : base("name=erp_lcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria_chamado> categoria_chamado { get; set; }
        public DbSet<cliente> clientes { get; set; }
        public DbSet<fornecedor> fornecedors { get; set; }
        public DbSet<pagamento> pagamentos { get; set; }
        public DbSet<subcategoria_chamado> subcategoria_chamado { get; set; }
        public DbSet<subcategoria2_chamado> subcategoria2_chamado { get; set; }
        public DbSet<subcategoria3_chamado> subcategoria3_chamado { get; set; }
    }
}
