//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SysAngular.Models
{
    
    
    public partial class fornecedor
    {
        public int for_cod { get; set; }
        public string for_nome { get; set; }
        public string for_rsocial { get; set; }
        public string for_ie { get; set; }
        public string for_cnpj { get; set; }
        public string for_cep { get; set; }
        public string for_endereco { get; set; }
        public string for_bairro { get; set; }
        public string for_fone { get; set; }
        public string for_cel { get; set; }
        public string for_email { get; set; }
        public string for_endnumero { get; set; }
        public string for_cidade { get; set; }
        public string for_estado { get; set; }
    }
}
