//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SysAngular.Models
{
    
    
    public partial class pagamento
    {
        public int pgt_cod { get; set; }
        public string pgt_credor { get; set; }
        public Nullable<System.DateTime> pgt_dtvenc { get; set; }
        public Nullable<System.DateTime> pgt_dtpgt { get; set; }
    }
}
